config/routes.rb
Rails.application.routes.draw do

  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback' # for use with Github, Facebook
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider

  get 'login' => 'user_sessions#new', as: :login
  post 'logout' => 'user_sessions#destroy', as: :logout
  get 'about' => 'pages#about', as: :about
  root to: 'pages#home'

  resources :user_sessions
  resources :users, except: [:index] do
    member do
      get :activate
      patch :default_group
    end
    collection do
      get :auto_complete
    end
  end

  # Only the collection routes of the children get member routes of the parent
  shallow do
    resources :user_groups do
      resources :users, module: :user_groups, only: [] do
        collection do
          get :show
        end
      end
      resources :groceries, except: [:update, :index, :edit] do
        resources :recipes, module: :groceries, only: [] do
          collection do
            patch :update
          end
        end
        resources :checkouts, module: :groceries, only: [:create] do
          collection do
            get :show
          end
        end
        resources :items, module: :groceries, only: [] do
          collection do
            get :show
            patch :update
          end
        end
        resources :receipts, module: :groceries, only: [:create] do
          collection do
            get :show
            post :confirm
          end
        end
        resources :items, only: [:update] do
          collection do
            get :auto_complete
          end
        end
        member do
          patch :receipt
          patch :do_checkout
          patch :update_store
          post :email_group
        end
      end
      member do
        get :payments
        patch :accept_invitation
        patch :do_payment
        patch :leave
      end
    end
  end
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  has_many :user_groups_users, class_name: UserGroupsUsers
  has_many :users, through: :user_groups_users
  has_many :items, -> { distinct }, through: :groceries
  has_many :groceries
  has_many :payments
  has_many :user_defaults, class_name: User, foreign_key: :user_group_default_id
  has_many :slack_messages, through: :slack_bot
  has_attached_file :banner, styles: { large: '800x600>', standard: '600x450>' }, default_url: 'user_groups/default1.jpg'
  has_one :slack_bot
  belongs_to :owner, class_name: User

  validates_attachment :banner, content_type: { content_type: /\Aimage\/.*\Z/ }
  validates :name, presence: true

  PUBLIC = 'public'.freeze
  PRIVATE = 'private'.freeze
  PRIVACY = [PUBLIC, PRIVATE]
  BANNER_IMAGES = ['default1', 'default2', 'default3'].freeze

  def self.public
    UserGroup.where(privacy: PUBLIC)
  end

  def self.private
    UserGroup.where(privacy: PRIVATE)
  end

  def privacy_items
    if privacy == PUBLIC
      Item.where(id: UserGroup.public.flat_map(&:item_ids))
    else
      items
    end
  end

  def active_groceries
    groceries.where(finished_at: nil)
  end

  def finished_groceries
    groceries.where.not(finished_at: nil)
  end

  def accepted_users
    user_groups_users.where(state: UserGroupsUsers::ACCEPTED).map(&:user)
  end

  def user_state(user)
    user_groups_users.find_by_user_id(user.id).state
  end
end

app/controllers/user_groups/users_controller.rb
class UserGroups::UsersController < ApplicationController
  include SplitController
  include ActiveModelSerializers
  initialize_split_controller :user_group

  def show
    render json: @user_group.users, user_group: @user_group
  end
end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
  extend HappyPath
  follow_happy_paths
  load_and_authorize_resource

  def show
    @components = {
      userManagement: user_management_params
    }
  end

  def new
    @new_data = new_data
    @banner_image = UserGroup::BANNER_IMAGES.sample
  end

  def create
    user_ids = user_group_params[:user_ids].split(',')
    user_ids << current_user.id unless user_ids.include?(current_user.id)
    @user_group.user_ids = user_ids
    @user_group.owner = current_user

    if @user_group.save
      @user_group.user_groups_users
                 .find_by_user_id(current_user.id)
                 .update_attribute(:state, UserGroupsUsers::ACCEPTED)

      current_user.update_attribute(:default_group, @user_group) unless current_user.default_group
      redirect_to @user_group, notice: 'Kit created! When you are ready, create your first grocery list.'
    else
      render json: @user_group.errors, status: :unprocessable_entity
    end
  end

  def edit
    @edit_data = edit_data
  end

  def payments
    grocery_payments = @user_group.finished_groceries.includes(:items).map do |grocery|
      receipt = grocery.receipt.url if grocery.receipt.file?
      {
        date: grocery.finished_at,
        id: grocery.id,
        name: grocery.name,
        receipt: receipt,
        total: grocery.payments_total.format,
        items: grocery.items.map do |item|
          {
            name: item[:name],
            price: item.grocery_item(grocery).price.format(symbol: false)
          }
        end,
        payments: grocery.payments.includes(:user).map do |payment|
          {
            id: payment.id,
            price: payment.price.format,
            payer: payment.user.name,
            image: payment.user.gravatar_url
          }
        end
      }
    end

    user_payments = @user_group.payments.includes(:payee, :payer).map do |payment|
      {
        date: payment.created_at,
        id: payment.id,
        reason: payment.reason,
        total: payment.price.format,
        payee: {
          name: payment.payee.name,
          image: payment.payee.gravatar_url
        },
        payer: {
          name: payment.payer.name,
          image: payment.payer.gravatar_url
        }
      }
    end

    @payment_data = {
      payments: (grocery_payments + user_payments)
        .sort_by { |payment| payment[:date].to_f }.reverse
    }
  end

  def update
    update_params = update_user_group_params
    update_params[:user_ids] = update_params[:user_ids].split(',')
    remaining_users = User.find(update_params[:user_ids])
    removed_users = @user_group.users - remaining_users

    removed_users.each do |user|
      if user.default_group == @user_group
        user.update_attribute(:default_group, nil)
      end
    end

    if params[:default_group]
      current_user.update_attribute(:default_group, @user_group)
    elsif current_user.default_group == @user_group
      current_user.update_attribute(:default_group, nil)
    end

    integrations = JSON.parse(params[:integrations]).with_indifferent_access
    slack = integrations[:slack]
    api_token = slack[:api_token]
    slackbot = @user_group.slack_bot

    if api_token.present?
      slackbot ||= SlackBot.create(user_group: @user_group)
      slackbot.slack_messages = slack[:message_types].map do |type, message_params|
        message = slackbot.slack_messages.find_or_create_by(message_type: type)

        message.tap do |updated_message|
          message.update!(message_params)
        end
      end
      slackbot.update!(api_token: api_token)
    else
      slackbot.destroy if slackbot
    end

    if @user_group.update(update_params)
      flash[:notice] = 'Kit successfully updated.'

      # Evict cache entry for user's abilities
      current_user.reload
      @current_ability = nil

      if can? :read, @user_group
        render json: { redirect_url: user_group_path(@user_group) }
      else
        render json: { redirect_url: user_groups_path }
      end
    else
      render json: @user_group.errors, status: :unprocessable_entity
    end
  end

  def accept_invitation
    @user_group_user = @user_group.user_groups_users.find_by_user_id(current_user.id)
    @user_group_user.state = UserGroupsUsers::ACCEPTED
    current_user.update_attribute(:default_group, @user_group) unless current_user.default_group

    if @user_group_user.save
      flash[:notice] = "You've been added to #{@user_group.name}."
      redirect_to @user_group
    else
      flash[:error] = 'Unable to join Kit.'
      redirect_to action: :index
    end
  end

  def leave
    @user_group.users.delete(current_user)
    current_user.update_attribute(:default_group, nil) if current_user.default_group == @user_group

    redirect_to user_groups_path, notice: "You have been removed from #{@user_group.name}'s Kit"
  end

  def do_payment
    Payment.create!(
      payment_params.merge(
        payer_id: current_user.id,
        user_group_id: @user_group.id
      )
    )
  end

private
  def user_group_params
    params.require(:user_group).permit(:name, :description, :privacy, :banner, :user_ids)
  end

  def payment_params
    params.require(:user_group).permit(:payee_id, :reason, :price)
  end

  def update_user_group_params
    params.require(:user_group).permit(
      :name,
      :description,
      :banner,
      :user_ids,
      :owner_id,
    )
  end

  def user_management_params
    {
      modal: '#pay-modal',
      url: do_payment_user_group_path(@user_group),
      users: {
        get_url: user_group_users_path(@user_group)
      }
    }
  end

  def new_data
    {
      title: 'Kit members',
      formElement: 'user_group_user_ids',
      buttonText: 'person',
      selection: [
        ActiveModelSerializers::SerializableResource.new(current_user).as_json
      ],
      modal: {
        id: 'change-members',
        queryUrl: auto_complete_users_path(image: true, q: ''),
        resultType: 'UserResult',
        input: {
          placeholder: 'Add friends to your Kit',
          queryField: 'query',
          fields: [
            {
              name: 'query',
              regex: '(.*)'
            }
          ]
        }
      }
    }
  end

  def edit_data
    {
      url: user_group_path(@user_group),
      modal: modal_data,
      multiselect: {
        buttonText: 'person'
      },
      userGroupTransfer: {
        owner: @user_group.owner.id,
      },
      userGroupBanner: {
        url: view_context.image_path(@user_group.banner.url(:standard))
      },
      userGroupSettings: {
        name: @user_group.name,
        description: @user_group.description,
        default_group: current_user.default_group == @user_group,
        badge: @user_group.privacy == UserGroup::PUBLIC ? 'badge' : 'badge secondary',
        privacyDisplay: @user_group.privacy.humanize
      },
      userGroupIntegrations: {
        slack: slack_data
      }
    }
  end

  def slack_data
    slack_messages = @user_group.slack_messages
    {
      api_token: @user_group.slack_bot.try(:api_token),
      name: 'Slack',
      message_types: CONFIGURABLES[:slack_messages].map do |message_data|
        message_data.dup.tap do |message|
          if slack_message = slack_messages.find_by_message_type(message_data[:id])
            message.merge!(slack_message.as_json
              .with_indifferent_access.slice(:format, :enabled))
          end
          message[:enabled] ||= false
        end
      end
    }
  end

  def modal_data
    {
      id: 'change-members',
      queryUrl: auto_complete_users_path(image: true, q: ''),
      resultType: 'UserResult',
      selection: @user_group.users.map do |user|
        {
          name: user.name,
          id: user.id,
          image: user.gravatar_url
        }
      end,
      input: {
        placeholder: 'Change who is in your Kit',
        queryField: 'query',
        fields: [
          {
            name: 'query',
            regex: '(.*)'
          }
        ]
      }
    }
  end
end

app/views/user_groups/edit.html.haml
.container
  = react_component 'UserGroupEdit', @edit_data

app/views/user_groups/index.html.haml
:coffee
  @current_user_id = #{current_user.id}

.container.user-groups-index
  .row
    .col.l12.align-center
      %h1 #{current_user.name}'s Kits
  - @user_groups.each_slice(3) do |groups|
    .row
      - groups.each do |group|
        - grocery = group.active_groceries.try(:first) || user_group_path(group)
        - invited = group.user_groups_users.find_by_user_id(current_user.id).state == UserGroupsUsers::INVITED
        .col.l4
          .card.image-wrapper.hoverable
            = link_to grocery do
              .card-image
                = image_tag group.banner.url(:standard)
                %span.card-title= group.name
            .card-content
              %p.truncate
                - if invited
                  You have been invited to join this Kit.
                - elsif group.description.present?
                  = group.description
                - elsif can? :update, group
                  Describe your
                  = link_to 'your Kit.', edit_user_group_path(group), class: :highlight
            .card-action
              - if invited
                = link_to 'Join', accept_invitation_user_group_path(group), method: :patch, class: 'highlight'
                %span.badge Invited
              - else
                = link_to 'Manage', user_group_path(group), class: 'highlight'
  .fixed-action-btn
    = link_to new_user_group_path, class: 'btn-floating btn-large' do
      %i.material-icons add

app/views/user_groups/metrics.html.haml
.container
  .metrics
    .row
      .columns.large-6
        .widget.facts
          .header
            %h1 Kit Metrics
          .main
            %p
              You have
              = pluralize @user_group.items.count, 'item'
              in your Kit and
              = pluralize @user_group.finished_groceries.count, 'grocery'
              finished.
              %br
              You really like #{@user_group.items.sort_by { |i| i.grocery_ids.count }.last.name }.
            = link_to 'Back to Kit', @user_group, class: 'button back'
      .columns.large-6
        .widget.metrics
          .header
            %h3 #{@user_group.name} Shopping History
          .main
            .row
              .columns.large-12
                = line_chart @metrics[:grocery_spending]
    .row
      .columns.large-6
        .widget.metrics
          .header
            %h3 #{@user_group.name} Grocery vs Cost
          .main
            .row
              .columns.large-12
                = column_chart @metrics[:grocery_cost]
      .columns.large-6
        .widget.metrics
          .header
            %h3 #{@user_group.name} Grocery vs Items
          .main
            .row
              .columns.large-12
                = column_chart @metrics[:grocery_items]

app/views/user_groups/new.html.haml
.container.user-groups-new
  = simple_form_for @user_group, remote: true do |f|
    .row
      .col.l8.offset-l2
        .card
          .card-content
            %h3 Create a Grocery Kit
            .row
              .col.l12
                %p A Kit maintains the list of people and groceries that are included in that Kit. Once you fill out some quick details we'll get started!
                .row.inputs
                  .col.l6.s12
                    = f.input :name, input_html: { class: 'input-field' }
                    = f.input :description, input_html: { class: 'input-field' }
                    = f.input :user_ids, as: :hidden
                  .col.l6.s12.privacy
                    Kit Privacy
                    = f.input :privacy, as: :radio_buttons, label: false, collection: UserGroup::PRIVACY, boolean_style: :inline, checked: UserGroup::PUBLIC
                    %p.public
                      Items you add to lists in
                      %strong Public
                      kits will be accessible by other public kits, so like word of mouth, users are able to share pricing info and reviews for these items.
                    %p.private.hide
                      A
                      %strong Private
                      kit is like starting from fresh. There won't be access to any of the items already available on SupermarKit, but any items that are created will only be visible to members of your kit.
    .row
      .col.l8.offset-l2
        .card
          .card-image
            = image_tag "user_groups/#{@banner_image}.jpg"
            %span.card-title Kit banner
          .card-content
            %p Add a custom image to your kit for you and your members to see.
          .card-action
            .input-field.file-field
              .btn
                %span File
                = f.input :banner, label: false, as: :file
              .file-path-wrapper
                %input.file-path.validate
  .row
    .col.l8.offset-l2.s12
      .card
        .card-content
          .row
            .col.l12.s12
              = react_component 'MultiselectForm', @new_data
        .card-action
          .btn.submit-group-form Create

app/views/user_groups/payments.html.haml
.container
  .user-groups-payments
    .row
      .col.l10.offset-l1
        %h1 Payment History
        = react_component 'Payments', @payment_data

app/views/user_groups/show.html.haml
.container
  %h1 Manage #{@user_group.name}
  .row
    .col.l6
      = react_component 'UserManagement', @components[:userManagement]
    .col.l6
      .card.kit-management
        .card-image
          = image_tag @user_group.banner.url(:standard)
          %span.card-title #{@user_group.name} Kit
        .card-content
          %ul.kit-actions
            - if can? :update, @user_group
              %li
                = icon 'cog'
                = link_to 'Change Kit Settings', edit_user_group_path(@user_group)
            - else
              - unless current_user.default_group == @user_group
                %li
                  = icon 'fa fa-check-circle'
                  = link_to 'Set as Default', default_group_user_path(current_user, user_group: @user_group), method: :patch
            %li
              = icon 'folder'
              = link_to 'Payment History', payments_user_group_path(@user_group)
            %li
              = icon 'shopping-cart'
              - if @user_group.active_groceries.length.nonzero?
                = link_to 'View Grocery List', @user_group.active_groceries.first
              - else
                = link_to 'Create Grocery List', new_user_group_grocery_path(@user_group)
            - unless can? :update, @user_group
              %li
                = icon 'fa fa-sign-out'
                = link_to 'Leave Kit', leave_user_group_path(@user_group), method: :patch