config/routes.rb
Rails.application.routes.draw do

  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback' # for use with Github, Facebook
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider

  get 'login' => 'user_sessions#new', as: :login
  post 'logout' => 'user_sessions#destroy', as: :logout
  get 'about' => 'pages#about', as: :about
  root to: 'pages#home'

  resources :user_sessions
  resources :users, except: [:index] do
    member do
      get :activate
      patch :default_group
    end
    collection do
      get :auto_complete
    end
  end

  # Only the collection routes of the children get member routes of the parent
  shallow do
    resources :user_groups do
      resources :users, module: :user_groups, only: [] do
        collection do
          get :show
        end
      end
      resources :groceries, except: [:update, :index, :edit] do
        resources :recipes, module: :groceries, only: [] do
          collection do
            patch :update
          end
        end
        resources :checkouts, module: :groceries, only: [:create] do
          collection do
            get :show
          end
        end
        resources :items, module: :groceries, only: [] do
          collection do
            get :show
            patch :update
          end
        end
        resources :receipts, module: :groceries, only: [:create] do
          collection do
            get :show
            post :confirm
          end
        end
        resources :items, only: [:update] do
          collection do
            get :auto_complete
          end
        end
        member do
          patch :receipt
          patch :do_checkout
          patch :update_store
          post :email_group
        end
      end
      member do
        get :payments
        patch :accept_invitation
        patch :do_payment
        patch :leave
      end
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  before_validation :format_name
  has_many :groceries_items, class_name: GroceriesItems, inverse_of: :item
  has_many :groceries, through: :groceries_items
  has_many :user_groups, through: :groceries
  has_and_belongs_to_many :recipes

  validates :name, presence: true

  accepts_nested_attributes_for :groceries_items

  scope :with_name, ->(q) { where('items.name LIKE ?', "%#{q}%").distinct }

  def grocery_item(grocery)
    groceries_items.find_by_grocery_id(grocery.id)
  end

  def self.format_name(name)
    name.en.singularize.capitalize
  end

  private

  def format_name
    self.name = Item.format_name(name)
  end
end

app/controllers/groceries/items_controller.rb
class Groceries::ItemsController < ApplicationController
  include SplitController
  include ActiveModelSerializers
  initialize_split_controller :grocery

  def show
    render json: @grocery.items, scope_name: :grocery, scope: @grocery, with_link: true
  end

  def update
    items = @grocery.items
    existing_items = Item.accessible_by(current_ability)

    updated_items = grocery_items_params[:items].map do |item_params|
      item_params[:groceries_items_attributes][:requester_id] ||= current_user.id
      item_params[:name] = Item.format_name(item_params[:name])
      existing_items.find_or_create_by(name: item_params[:name]).tap do |item|
        item.update!(item_params)
      end
    end

    @grocery.items.delete(items - updated_items)
    head :ok
  end

  private

  def grocery_items_params
    params.require(:grocery).permit(
      items: [
        :id,
        :name,
        groceries_items_attributes: [
          :id,
          :quantity,
          :price,
          :units,
          :requester_id,
          :grocery_id
        ]
      ]
    )
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  extend HappyPath
  include ActiveModelSerializers
  follow_happy_paths
  load_and_authorize_resource :grocery
  load_and_authorize_resource :item, through: :grocery, shallow: true

  def update
    grocery_item = @item.grocery_item(@grocery)
    if @item.update(item_params)
      render json: {
        grocery_item: SerializableResource.new(grocery_item).as_json,
        updated_grocery_item: SerializableResource.new(grocery_item.reload).as_json
      }
    else
      render json: @item.errors, status: :unprocessable_entity
    end
  end

  def auto_complete
    items = @grocery.user_group.privacy_items.select(:id, :description, :name)
                    .with_name(params[:q]).order('LENGTH(items.name) ASC')
                    .limit(5)

    render json: {
      data: items.map do |item|
        {
          id: item.id,
          name: item.name,
          description: item.description
        }
      end
    }
  end

private
  def item_params
    params.require(:item).permit(
      :name,
      :description,
      groceries_items_attributes: [
        :price,
        :price_cents,
        :id,
        :quantity,
        :grocery_id,
        :units
      ]
    )
  end

  def groceries_items_params
    params.require(:item).require(:groceries_items_attributes).permit(
      :price,
      :price_cents,
      :id,
      :quantity,
      :grocery_id,
      :units
    )
  end
end

app/views/items/edit.html.haml
.container.items-edit
  .row
    .columns.large-8.large-centered
      .widget
        .row
          .columns.large-8.large-centered
            .header
              %h3 Edit Item
            .main
              .row
                = simple_form_for @item do |f|
                  .columns.large-12
                    = f.input :name
                    = f.input :description, as: :text
                    .row
                      .columns.large-6
                        = f.input :groceries_items, label: "Grocery", collection: @item.groceries_items, selected: 1, label_method: ->(g) { Grocery.find(g.grocery_id).name }
                      .columns.large-6
                        = f.simple_fields_for :groceries_items do |g|
                          = g.input :quantity, input_html: { class: 'quantity-input', id: "grocery-item-#{g.object.id}" }

app/views/items/new.html.haml
.container.items-new
  .row
    .columns.large-8.large-centered
      .widget
        .row
          .columns.large-8.large-centered
            .header
              %h3 New item
            .main
              = simple_form_for [@grocery, @item] do |f|
                .row
                  .columns.large-12
                    .row
                      .columns.large-12
                        = f.input :name
                        = f.input :description, as: :text
                    .row
                      .columns.large-4
                        = label_tag :price
                        = text_field_tag :price
                        = f.input :price, as: :hidden, input_html: { value: 0 }
                      .columns.large-4.end
                        = f.simple_fields_for :groceries_items, @groceries_items do |g|
                          = g.input :quantity, input_html: { value: 1 }
                          = g.input :grocery_id, as: :hidden, input_html: { value: @grocery.id }
                    .row
                      .columns.large-12
                        = f.button :submit, 'Create', class: 'button radius'

app/views/items/show.html.haml
.container.items-show
  .row
    .columns.large-8.large-centered
      .widget
        .header
          %h3 Item
        .main
          .row
            .columns.large-12
              .row
                .columns.large-12
                  %label Name
                  %p= @item.name
              %hr
              .row
                .columns.large-12
                  %label Description
                  %p= @item.description
              %hr
              .row
                .columns.large-12
                  = link_to 'Edit Item', edit_item_path(@item), class: 'button'