config/routes.rb
Rails.application.routes.draw do

  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback' # for use with Github, Facebook
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider

  get 'login' => 'user_sessions#new', as: :login
  post 'logout' => 'user_sessions#destroy', as: :logout
  get 'about' => 'pages#about', as: :about
  root to: 'pages#home'

  resources :user_sessions
  resources :users, except: [:index] do
    member do
      get :activate
      patch :default_group
    end
    collection do
      get :auto_complete
    end
  end

  # Only the collection routes of the children get member routes of the parent
  shallow do
    resources :user_groups do
      resources :users, module: :user_groups, only: [] do
        collection do
          get :show
        end
      end
      resources :groceries, except: [:update, :index, :edit] do
        resources :recipes, module: :groceries, only: [] do
          collection do
            patch :update
          end
        end
        resources :checkouts, module: :groceries, only: [:create] do
          collection do
            get :show
          end
        end
        resources :items, module: :groceries, only: [] do
          collection do
            get :show
            patch :update
          end
        end
        resources :receipts, module: :groceries, only: [:create] do
          collection do
            get :show
            post :confirm
          end
        end
        resources :items, only: [:update] do
          collection do
            get :auto_complete
          end
        end
        member do
          patch :receipt
          patch :do_checkout
          patch :update_store
          post :email_group
        end
      end
      member do
        get :payments
        patch :accept_invitation
        patch :do_payment
        patch :leave
      end
    end
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy], raise: false
  skip_authorization_check

  def new
  end

  def create
    if @user = login(session_params[:email], session_params[:password])
      redirect_back_or_to root_path
    else
      render json: 'Incorrect login information.', status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to login_path
  end

  private

  def session_params
    params.require(:user_session).permit(:email, :password)
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.haml
.container.new-user-session
  .row
    .col.l8.offset-l2
      .card
        = simple_form_for :user_session, url: user_sessions_path, remote: true do |f|
          .card-content
            .row
              .col.l12
                %h1 Login
            .row
              .col.l6.s12
                .input-field= f.input :email
                .input-field= f.input :password
              .col.l6.s12
                = render partial: 'components/social', locals: { button_label: 'Login with' }
          .card-action
            = f.button :submit, 'Login'